<div style="
    background: linear-gradient(135deg, #667eea, #764ba2);
    padding: 60px 20px;
    text-align: center;
    border-radius: 20px;
    box-shadow: 0 20px 40px rgba(0,0,0,0.25);
    font-family: 'Segoe UI', Helvetica, sans-serif;
    color: white;
">

  <h1 style="
        font-size: 42px;
        font-weight: 700;
        letter-spacing: 1px;
        margin-bottom: 20px;
    ">
        Codroidhub API Web Scraping
    </h1>

 <p style="
        font-size: 18px;
        opacity: 0.9;
        margin-bottom: 30px;
    ">
        Extracting Real-Time Data using Python & API
    </p>

  <span style="
        background: white;
        color: #764ba2;
        padding: 12px 30px;
        border-radius: 50px;
        font-weight: 600;
        font-size: 18px;
        box-shadow: 0 8px 20px rgba(0,0,0,0.15);
        transition: 0.3s;
    ">
        Mansi Sharma
    </span>

</div>

In [2]:
import pandas as pd
from bs4 import BeautifulSoup
import requests

In [3]:
url="https://puirf.codroidhub.com/api/api/v1/instruments/user/getHomeFacilities?upcomingLimit=2"

In [4]:
headers = {"user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/144.0.0.0 Safari/537.36"}

In [5]:
response = requests.get(url,headers= headers)

In [6]:
response.status_code

200

In [7]:
data= response.json()

In [8]:
main_data=data["data"]

In [9]:
main_data.keys()

dict_keys(['saif', 'cil', 'upcoming'])

In [10]:
saif_data = main_data["saif"]

In [11]:
name_list = []
unique_id_list = []

for saif in saif_data:
    name_list.append(saif["name"])
    unique_id_list.append(saif["uniqueId"])
    
df = pd.DataFrame({
    "Name": name_list,
    "Unique_Id": unique_id_list
})
df

                                            Name             Unique_Id
0                                         FT NMR                   NMR
1       MALDI TOF SYNAPT XS HD MASS SPECTROMETER                  LCMS
2                      X ray Photon Spectroscopy                   XPS
3                              X Ray Diffraction                   XRD
4    Field Emission Scanning Electron Microscopy                FE-SEM
5                   SCANNING ELECTRON MICROSCOPY                   SEM
6   INDUCTIVELY COUPLED PLASMA MASS SPECTROMETRY                 ICPMS
7                    THERMO GRAVIMETRIC ANALYSIS                   TGA
8                                            DSC                   DSC
9                                   BET ANALYZER                   BET
10                                  Fluorescence                 FLURO
11                               CD Spectrometer                    CD
12                                        UV VIS                UV-VIS
13                                  ELLIPSOMETER          ELLIPSOMETER
14                                   POLARIMETER           POLARIMETER
15                               LIQUID NITROGEN                   LN2
16                          Critical point dryer  Critical point dryer
17                               ULTRA MICROTOME       ULTRA MICROTOME
18                                 ZETA ANALYZER                  Zeta

In [12]:
cil_data = main_data["cil"]

In [13]:
name_list = []
unique_id_list = []

for cil in cil_data:
    name_list.append(cil["name"])
    unique_id_list.append(cil["uniqueId"])
    
df = pd.DataFrame({
    "Name": name_list,
    "Unique_Id": unique_id_list
})
df

                                               Name Unique_Id
0  HIGH RESOLUTION TRANSMISSION ELECTRON MICROSCOPY     HRTEM
1              Gas Chromatography Mass Spectrometry      GCMS
2                               Confocal microscopy  Confocal
3                      Small Angle X ray Scattering      SAXS
4                                            CHNS O    CHNS O
5                                Raman Spectroscopy     RAMAN
6                                         Rheometer      RHEO
7                                              FTIR      FTIR

In [14]:
upcoming_data = main_data["upcoming"]

In [15]:
name_list = []
unique_id_list = []

for upcoming in upcoming_data:
    name_list.append(upcoming["name"])
    unique_id_list.append(upcoming["uniqueId"])
    
df = pd.DataFrame({
    "Name": name_list,
    "Unique_Id": unique_id_list
})
df

                      Name Unique_Id
0  Atomic Force Microscopy       AFM

<html>
<head>
    <title></title>
</head>
<body 
style="background: linear-gradient(to right, #74ebd5, #ACB6E5); 
    text-align: center; 
             font-family: Arial; 
             margin: 0; 
             padding-top: 150px;">

<div style="background-color: white; 
                display: inline-block; 
                padding: 40px 60px; 
                border-radius: 15px; 
                box-shadow: 0 8px 20px rgba(0,0,0,0.2);">

  <h1 style="color: #2c3e50; font-size: 42px; margin-bottom: 10px;">
            Thank You!
        </h1>

<p style="font-size: 22px; color: #6c5ce7; font-weight: bold;">
            Mansi Sharma
        </p>

  </div>

</body>
</html>